#
# see https://github.com/helix-editor/helix/wiki/Language-Server-Configurations
#
#
# debug lsp
# hx -v 
# tail -f ~/.cache/helix/helix.log




[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]
# config = { userLanguages = { rust = "html", "*.rs" = "html" } }

[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.rust-analyzer.config.cargo]
features = "all"

[[language]]
name = "rust"
auto-format = true

[[language]]
name = "typescript"
language-servers = [ { name = "efm-lsp-prettier", only-features = [ "format" ] }, "typescript-language-server","vscode-eslint-language-server",]


[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "tailwindcss-ls" ]

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "tailwindcss-ls" ]

[[language]]
name = "jsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls","vscode-eslint-language-server", ]

[[language]]
name = "tsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls","vscode-eslint-language-server", ]

[[language]]
name = "svelte"
language-servers = [ "svelteserver", "tailwindcss-ls" ]
